// <auto-generated from scripts/analyze_schedule_timing.py — do not edit by hand>
using System.Collections.Generic;

namespace Hiatme_Tool_Suite_v3
{
    internal static partial class SupeyDeskScheduleTiming
    {
        private static readonly Dictionary<string, double> ClientEarlyPuAllowanceMinutes =
            new Dictionary<string, double>(System.StringComparer.OrdinalIgnoreCase)
        {
            { "DIONNE, BENJAMIN R", 105 },
            { "JOLICOEUR, JEFFREY", 105 },
            { "SWAN, SHERI S", 100 },
            { "TRASK, ADELMA GLADYS", 90 },
            { "YEATON, MARY", 90 },
            { "DESROCHERS, DAVID P", 75 },
            { "PHILLIPS, MICAH J", 75 },
            { "SCHWARTZ, RYAN B", 65 },
            { "EDDY, ALYSSA A", 65 },
            { "NOWLAND, FREYJHA V", 65 },
            { "BRYANT, LOGAN T", 65 },
            { "HOLT, CARMAN G", 65 },
            { "HEINO, STASHA B", 65 },
            { "HOWARD, DONNA M", 65 },
            { "LAGASSE, JILL LEE", 65 },
            { "BURKHARDT, JOEL DAVID", 65 },
            { "CUTLER, JESSICA", 65 },
            { "GRAHAM, JASON PAUL", 65 },
            { "LIZOTTE, TAMMY M", 60 },
            { "GILMORE, ABRAHAM L", 60 },
            { "THEBERGE, STACY L", 50 },
            { "QUADROS, LAURA L", 50 },
            { "BRYANT, MICHAEL DENNIS", 50 },
            { "MORIN, TODD J", 50 },
            { "DELMISSIER, PATRICK", 50 },
            { "RING, ARNOLD", 50 },
            { "EINSMANN, MARK ROBERT", 50 },
            { "RIDLON, BENJAMIN", 50 },
            { "LABRECQUE, DYLAN M", 50 },
            { "DRAPER, KEITH R", 50 },
            { "BOOKER, MEGAN M", 50 },
            { "CATIVERA, JENNIFER E", 50 },
            { "MILLER, MARIA", 50 },
            { "YEATON, DEVIN M", 50 },
            { "TAYLOR, FREDERICK R", 50 },
            { "ST HILAIRE, TRINA L", 50 },
            { "LOZIER, SUSAN A.", 50 },
            { "ORMON, JONATHAN", 50 },
            { "MAUNG, VICTOR K", 50 },
            { "FARAH, IDRISS B", 50 },
            { "EMERY, KALA S", 50 },
            { "MYER, JEREMY DEAN", 50 },
            { "BELIVEAU, JUSTIN T", 50 },
            { "SEGER, NICOLE J", 50 },
            { "LOUGH, JOHN PROULX", 50 },
            { "HUCKABEY, ALAN", 45 },
            { "OUELLETTE, PAULA ANNE", 45 },
            { "BOISVERT, GAIL P", 45 },
            { "LEVASSEUR, LORI C", 45 },
            { "THUOTTE, RICHARD J", 45 },
        };

        private static readonly HashSet<string> ClientNoEarlyPu =
            new HashSet<string>(System.StringComparer.OrdinalIgnoreCase)
        {
            "BROWN, JOSHUA M",
            "TUTTLE, SIERRA B",
            "BROWN, JOSHUA M",
            "TUTTLE, SIERRA B",
        };

        private static readonly Dictionary<string, double> DoHubEarlyPuAllowanceMinutes =
            new Dictionary<string, double>(System.StringComparer.OrdinalIgnoreCase)
        {
            { "20_EAST", 40 },
            { "23_CROSS", 50 },
            { "618_MAIN", 35 },
            { "63_BROAD", 50 },
            { "646_MAIN", 40 },
            { "FALCON", 50 },
            { "MANLEY", 65 },
            { "MINOT", 65 },
        };

        private static readonly Dictionary<string, double> PuHubEarlyPuAllowanceMinutes =
            new Dictionary<string, double>(System.StringComparer.OrdinalIgnoreCase)
        {
            { "PU_23_CROSS", 60 },
            { "PU_646_MAIN", 25 },
            { "PU_MANLEY", 90 },
            { "PU_MINOT_AUBURN", 25 },
        };
    }
}
