"""Emit SupeyDeskScheduleTiming.Rules.cs from schedule-timing-analysis.json."""
import json
from pathlib import Path

JSON = Path(__file__).resolve().parent / "schedule-timing-analysis.json"
OUT = Path(__file__).resolve().parents[1] / (
    "Hiatme Tool Suite v3/Hiatme Tool Suite v3/SupeyDeskScheduleTiming.Rules.cs"
)


def main() -> None:
    data = json.loads(JSON.read_text(encoding="utf-8"))
    clients = data.get("client_early_pu_allowance_p75", [])
    no_early = [x[0] for x in data.get("client_no_early_pu", [])]
    do_hubs = data.get("do_hub_pu_do_gap_p75", {})
    pu_hubs = data.get("pu_hub_pu_do_gap_p75", {})

    lines = [
        "// <auto-generated from scripts/analyze_schedule_timing.py — do not edit by hand>",
        "using System.Collections.Generic;",
        "",
        "namespace Hiatme_Tool_Suite_v3",
        "{",
        "    internal static partial class SupeyDeskScheduleTiming",
        "    {",
        "        private static readonly Dictionary<string, double> ClientEarlyPuAllowanceMinutes =",
        "            new Dictionary<string, double>(System.StringComparer.OrdinalIgnoreCase)",
        "        {",
    ]
    for name, _n, p75 in clients:
        safe = name.replace('"', '\\"')
        lines.append(f'            {{ "{safe}", {p75} }},')
    lines.append("        };")
    lines.append("")
    lines.append("        private static readonly HashSet<string> ClientNoEarlyPu =")
    lines.append("            new HashSet<string>(System.StringComparer.OrdinalIgnoreCase)")
    lines.append("        {")
    for name in no_early:
        safe = name.replace('"', '\\"')
        lines.append(f'            "{safe}",')
    lines.append('            "BROWN, JOSHUA M",')
    lines.append('            "TUTTLE, SIERRA B",')
    lines.append("        };")
    lines.append("")
    lines.append("        private static readonly Dictionary<string, double> DoHubEarlyPuAllowanceMinutes =")
    lines.append("            new Dictionary<string, double>(System.StringComparer.OrdinalIgnoreCase)")
    lines.append("        {")
    for hub, info in sorted(do_hubs.items()):
        lines.append(f'            {{ "{hub}", {info["p75"]} }},')
    lines.append("        };")
    lines.append("")
    lines.append("        private static readonly Dictionary<string, double> PuHubEarlyPuAllowanceMinutes =")
    lines.append("            new Dictionary<string, double>(System.StringComparer.OrdinalIgnoreCase)")
    lines.append("        {")
    for hub, info in sorted(pu_hubs.items()):
        lines.append(f'            {{ "{hub}", {info["p75"]} }},')
    lines.append("        };")
    lines.append("    }")
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} ({len(clients)} clients)")


if __name__ == "__main__":
    main()
